# Generated by Django 4.2.4 on 2023-10-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Title", max_length=1000, null=True),
                ),
                ("text", models.TextField(default="Sample text.", null=True)),
                (
                    "snippet",
                    models.CharField(
                        default="Sample snippet.", max_length=300, null=True
                    ),
                ),
                ("url", models.CharField(max_length=100, null=True)),
                (
                    "pattern",
                    models.CharField(default="None", max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(default="Query", max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("recall", models.FloatField()),
                ("precision", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("error", models.FloatField()),
                ("Fmeasure", models.FloatField()),
                ("avgPrecision", models.FloatField(default=0.0)),
            ],
        ),
    ]
