# Generated by Django 3.2.7 on 2021-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooleanSearch', '0002_alter_document_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(default='Sample text.', null=True),
        ),
    ]
